// components/sidebar/index.tsx
'use client'

import Link from 'next/link'
import { useParams, usePathname } from 'next/navigation'
import type { JSX } from 'react'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import {
  AdIcon,
  AdLogo,
  checkIsStaff,
  type DockItemInterface,
  getDockItems,
  getToolbarLogoutItem,
  getToolbarNavItems,
  NucDockPopovers,
  sessionStorageGetItem,
} from 'nucleify'

import './_index.scss'

function isStaffOnly(item: DockItemInterface): boolean {
  const url = item.url ?? ''
  return (
    url.endsWith('/admin') ||
    url.endsWith('/structural') ||
    url.endsWith('/translations') ||
    url.endsWith('/builder')
  )
}

export function NucSidebar(): JSX.Element {
  const params = useParams()
  const pathname = usePathname()
  const { t } = useTranslation()
  const [isStaff, setIsStaff] = useState(false)

  const lang = (params?.lang as string) || 'en'
  const dockItems = useMemo(() => getDockItems(lang, t), [lang, t])

  const navItems = useMemo(() => getToolbarNavItems(dockItems), [dockItems])

  const logoutItem = useMemo(() => getToolbarLogoutItem(dockItems), [dockItems])

  useEffect(() => {
    const userRole = sessionStorageGetItem('user_role')
    if (userRole) {
      setIsStaff(checkIsStaff(userRole))
    }
  }, [])

  function isActive(item: DockItemInterface): boolean {
    if (!item.url) return false

    const [path, hash] = item.url.split('#')
    const currentHash =
      typeof window !== 'undefined' ? window.location.hash : ''

    if (hash) {
      return pathname === path && currentHash === `#${hash}`
    }

    return pathname === path || pathname.startsWith(`${path}/`)
  }

  return (
    <aside className={`nuc-sidebar${isStaff ? ' staff' : ''}`}>
      <div className="nuc-sidebar-header">
        <Link
          href={`/${lang}/home`}
          className="nuc-sidebar-logo"
          aria-label="Nucleify home"
        >
          <AdLogo nuiType="main" dimensions={32} />
          <span className="nuc-sidebar-logo-label">Nucleify</span>
        </Link>
      </div>

      <nav className="nuc-sidebar-nav" aria-label="Main navigation">
        <ul className="nuc-sidebar-list">
          {navItems.map((item) => (
            <li
              key={item.label}
              className={[
                'nuc-sidebar-item',
                isActive(item) ? 'is-active' : '',
                isStaffOnly(item) ? 'is-staff-only' : '',
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {item.url ? (
                <Link
                  href={item.url}
                  className="nuc-sidebar-link"
                  {...(item.nuiType ? { 'data-nui-type': item.nuiType } : {})}
                >
                  {item.icon ? (
                    <AdIcon
                      icon={item.icon}
                      nuiType={item.nuiType}
                      size="1.25em"
                    />
                  ) : null}
                  <span>{item.label}</span>
                </Link>
              ) : null}
            </li>
          ))}
        </ul>
      </nav>

      <div className="nuc-sidebar-footer">
        <p className="nuc-sidebar-section-label">{t('dock-tools')}</p>
        <NucDockPopovers position="bottom" variant="sidebar" />

        {logoutItem ? (
          <ul className="nuc-sidebar-list">
            <li className="nuc-sidebar-item">
              <button
                type="button"
                className="nuc-sidebar-link is-logout"
                onClick={logoutItem.click}
              >
                {logoutItem.icon ? (
                  <AdIcon icon={logoutItem.icon} size="1.25em" />
                ) : null}
                <span>{logoutItem.label}</span>
              </button>
            </li>
          </ul>
        ) : null}
      </div>
    </aside>
  )
}

// components/sidebar/index.vue
<template>
  <aside class="nuc-sidebar" :class="{ staff: isStaff }">
    <div class="nuc-sidebar-header">
      <nuxt-link
        :to="`/${lang}/home`"
        class="nuc-sidebar-logo"
        aria-label="Nucleify home"
      >
        <ad-logo nui-type="main" :dimensions="32" />
        <span class="nuc-sidebar-logo-label">Nucleify</span>
      </nuxt-link>
    </div>

    <nav class="nuc-sidebar-nav" aria-label="Main navigation">
      <ul class="nuc-sidebar-list">
        <li
          v-for="item in navItems"
          :key="item.label"
          class="nuc-sidebar-item"
          :class="{
            'is-active': isActive(item),
            'is-staff-only': isStaffOnly(item),
          }"
        >
          <nuxt-link
            v-if="item.url"
            :to="item.url"
            class="nuc-sidebar-link"
            :nui-type="item.nuiType"
          >
            <ad-icon
              v-if="item.icon"
              :icon="item.icon"
              :nui-type="item.nuiType"
              size="1.25em"
            />
            <span>{{ item.label }}</span>
          </nuxt-link>
        </li>
      </ul>
    </nav>

    <div class="nuc-sidebar-footer">
      <p class="nuc-sidebar-section-label">{{ t('dock-tools') }}</p>
      <nuc-dock-popovers position="bottom" variant="sidebar" />

      <ul v-if="logoutItem" class="nuc-sidebar-list">
        <li class="nuc-sidebar-item">
          <button
            type="button"
            class="nuc-sidebar-link is-logout"
            @click="logoutItem.click"
          >
            <ad-icon
              v-if="logoutItem.icon"
              :icon="logoutItem.icon"
              size="1.25em"
            />
            <span>{{ logoutItem.label }}</span>
          </button>
        </li>
      </ul>
    </div>
  </aside>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import {
  checkIsStaff,
  getDockItems,
  getToolbarLogoutItem,
  getToolbarNavItems,
  NucDockPopovers,
  sessionStorageGetItem,
  type DockItemInterface,
} from 'nucleify'

const route = useRoute()
const { t } = useI18n()
const isStaff = ref(false)

const lang = computed(() => (route.params.lang as string) || 'en')

const navItems = computed(() => getToolbarNavItems(getDockItems(lang.value, t)))

const logoutItem = computed(() =>
  getToolbarLogoutItem(getDockItems(lang.value, t))
)

function isStaffOnly(item: DockItemInterface): boolean {
  const url = item.url ?? ''
  return (
    url.endsWith('/admin') ||
    url.endsWith('/structural') ||
    url.endsWith('/translations') ||
    url.endsWith('/builder')
  )
}

function isActive(item: DockItemInterface): boolean {
  if (!item.url) return false

  const [path, hash] = item.url.split('#')
  const currentPath = route.path
  const currentHash = route.hash

  if (hash) {
    return currentPath === path && currentHash === `#${hash}`
  }

  return currentPath === path || currentPath.startsWith(`${path}/`)
}

onMounted(() => {
  isStaff.value = checkIsStaff(sessionStorageGetItem('user_role')!)
})
</script>

<style lang="scss">
@import 'index';
</style>
