// index.tsx
'use client'

import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import {
  AdDock,
  AdIcon,
  AdLogo,
  AdRadioButton,
  checkIsStaff,
  type DockItemInterface,
  getDockItems,
  localStorageGetItem,
  localStorageSetItem,
  NucDockPopovers,
  type PositionType,
  positions,
  sessionStorageGetItem,
} from 'nucleify'
import './_index.scss'

const LOCAL_STORAGE_KEY = 'dock-position'

export const NucDock = () => {
  const params = useParams()
  const { t } = useTranslation()
  const lang = (params?.lang as string) || 'en'

  const [position, setPosition] = useState<PositionType>('bottom')
  const [isStaff, setIsStaff] = useState(false)

  const itemTemplate = (item: DockItemInterface) => {
    if (item.logo) {
      return (
        <Link href={item.url || '#'} aria-label={item.label}>
          <AdLogo adType="main" />
        </Link>
      )
    }

    if (item.icon && (item.url || item.click)) {
      return (
        <Link
          href={item.url || '#'}
          aria-label={item.label}
          onClick={(e) => {
            if (item.click) {
              if (!item.url) e.preventDefault()
              item.click()
            }
          }}
          title={item.label}
        >
          <AdIcon
            icon={item.icon}
            className="item"
            adType={item.adType}
            size="1.7em"
          />
        </Link>
      )
    }

    if (item.icon && !item.url && !item.click) {
      return (
        <span title={item.label}>
          <AdIcon
            icon={item.icon}
            className="item disabled-item"
            size="1.7em"
          />
        </span>
      )
    }

    if (item.label === 'position') {
      return (
        <div className="dock-position-buttons">
          {positions.map((pos) => (
            <AdRadioButton
              key={pos.value}
              name="dock-position"
              value={pos.value}
              checked={position === pos.value}
              onChange={(event) => {
                if (event.checked) {
                  setPosition(event.value as PositionType)
                }
              }}
              className={`${pos.value} flex`}
              adType="main"
              unstyled
            />
          ))}
        </div>
      )
    }

    return null
  }

  const dockItems = useMemo(() => {
    const items = getDockItems(lang, t)
    return items.map((item) => ({
      ...item,
      template: () => itemTemplate(item),
    }))
  }, [lang, t, position])

  const setDockPositionForScreenSize = () => {
    if (window.innerWidth === 992) {
      setPosition('bottom')
    }
  }

  useEffect(() => {
    const savedPosition = localStorageGetItem(LOCAL_STORAGE_KEY)
    if (savedPosition) {
      setPosition(savedPosition as PositionType)
    }

    const userRole = sessionStorageGetItem('user_role')
    if (userRole) {
      setIsStaff(checkIsStaff(userRole))
    }

    window.addEventListener('resize', setDockPositionForScreenSize)
    return () => {
      window.removeEventListener('resize', setDockPositionForScreenSize)
    }
  }, [])

  useEffect(() => {
    localStorageSetItem(LOCAL_STORAGE_KEY, position)
  }, [position])

  return (
    <>
      <NucDockPopovers position={position} />

      <AdDock
        model={dockItems}
        position={position}
        className={`nuc-dock${isStaff ? ' staff' : ''}`}
      />
    </>
  )
}

export default NucDock

// index.vue
<template>
  <nuc-dock-popovers :position="position" />

  <ad-dock
    :model="dockItems"
    :position="position"
    :class="{ staff: isStaff }"
    class="nuc-dock"
  >
    <template #item="{ item }">
      <a v-if="item.logo" :href="item.url" :aria-label="item.label">
        <ad-logo ad-type="main" />
      </a>

      <nuxt-link
        v-if="item.icon && (item.url || item.click)"
        :to="item.url"
        :aria-label="item.label"
        v-tooltip.top="item.label"
      >
        <ad-icon
          :icon="item.icon"
          class="item"
          :ad-type="item.adType"
          @click="item.click"
          size="1.7em"
        />
      </nuxt-link>

      <ad-icon
        v-if="item.icon && !item.url && !item.click"
        v-tooltip="item.label"
        :icon="item.icon"
        class="item disabled-item"
        size="1.7em"
        @click="item.click"
      />

      <div v-if="item.label === 'position'" class="dock-position-buttons">
        <ad-radio-button
          v-for="pos in positions"
          :key="pos.value"
          v-model="position"
          :value="pos.value"
          :class="pos.value"
          ad-type="main"
          class="flex"
          unstyled
        />
      </div>
    </template>
  </ad-dock>
</template>

<script setup lang="ts">
import { useRoute } from 'nuxt/app'
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import {
  checkIsStaff,
  getDockItems,
  localStorageGetItem,
  localStorageSetItem,
  NucDockPopovers,
  positions,
  sessionStorageGetItem,
  type PositionType,
} from 'nucleify'

const route = useRoute()
const { t } = useI18n()
const dockItems = computed(() => {
  const lang = (route.params.lang as string) || 'en'
  return getDockItems(lang, t)
})

const LOCAL_STORAGE_KEY = 'dock-position'

const position = ref<PositionType>('bottom')
const isStaff = ref(false)

function setDockPositionForScreenSize() {
  if (window.innerWidth == 992) {
    position.value = 'bottom'
  }
}

onMounted(async () => {
  const savedPosition = localStorageGetItem(LOCAL_STORAGE_KEY)
  if (savedPosition) {
    position.value = savedPosition as PositionType
  }

  isStaff.value = checkIsStaff(sessionStorageGetItem('user_role')!)

  window.addEventListener('resize', setDockPositionForScreenSize)
})

watch(position, (newPosition: PositionType) => {
  localStorageSetItem(LOCAL_STORAGE_KEY, newPosition)
})
</script>

<style lang="scss">
@import 'index';
</style>
