// components/popovers/index.tsx
'use client'

import type { JSX } from 'react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'

import type { PositionType } from 'nucleify'
import { AdIcon, NucFriendship, NucShare, NucTerminal } from 'nucleify'

interface NucDockPopoversProps {
  position?: PositionType
  variant?: 'dock' | 'sidebar'
}

export function NucDockPopovers({
  position = 'bottom',
  variant = 'dock',
}: NucDockPopoversProps): JSX.Element {
  const { t } = useTranslation()
  const [isExpanded, setIsExpanded] = useState(false)
  const isSidebar = variant === 'sidebar'

  return (
    <div
      className={[
        position,
        variant,
        'nuc-dock-popovers',
        isSidebar || isExpanded ? 'expanded' : '',
      ]
        .filter(Boolean)
        .join(' ')}
    >
      {!isSidebar ? (
        <button
          type="button"
          className="nuc-dock-popovers-toggle"
          aria-expanded={isExpanded}
          aria-label={t('dock-tools-toggle')}
          onClick={() => setIsExpanded((value) => !value)}
        >
          <AdIcon
            icon={isExpanded ? 'mdi:chevron-down' : 'mdi:chevron-up'}
            size="1.1em"
          />
        </button>
      ) : null}

      <div className="nuc-dock-popovers-panel">
        {isSidebar ? (
          <ul className="nuc-sidebar-list">
            <li className="nuc-sidebar-item">
              <NucShare variant="sidebar" position={position} />
            </li>
            <li className="nuc-sidebar-item">
              <NucFriendship variant="sidebar" position={position} />
            </li>
            <li className="nuc-sidebar-item">
              <NucTerminal variant="sidebar" position={position} />
            </li>
          </ul>
        ) : (
          <>
            <NucShare position={position} />
            <NucFriendship position={position} />
            <NucTerminal position={position} />
          </>
        )}
      </div>
    </div>
  )
}

// components/popovers/index.vue
<template>
  <div
    class="nuc-dock-popovers"
    :class="[position, variant, { expanded: variant === 'sidebar' || isExpanded }]"
  >
    <button
      v-if="variant !== 'sidebar'"
      type="button"
      class="nuc-dock-popovers-toggle"
      :aria-expanded="isExpanded"
      :aria-label="t('dock-tools-toggle')"
      @click="isExpanded = !isExpanded"
    >
      <ad-icon
        :icon="isExpanded ? 'mdi:chevron-down' : 'mdi:chevron-up'"
        size="1.1em"
      />
    </button>

    <div class="nuc-dock-popovers-panel">
      <ul v-if="variant === 'sidebar'" class="nuc-sidebar-list">
        <li class="nuc-sidebar-item">
          <nuc-share variant="sidebar" :position="position" />
        </li>
        <li class="nuc-sidebar-item">
          <nuc-friendship variant="sidebar" :position="position" />
        </li>
        <li class="nuc-sidebar-item">
          <nuc-terminal variant="sidebar" :position="position" />
        </li>
      </ul>

      <template v-else>
        <nuc-share :position="position" />
        <nuc-friendship :position="position" />
        <nuc-terminal :position="position" />
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from 'vue-i18n'

import type { PositionType } from 'nucleify'

withDefaults(
  defineProps<{
    position?: PositionType
    variant?: 'dock' | 'sidebar'
  }>(),
  {
    position: 'bottom',
    variant: 'dock',
  }
)

const { t } = useI18n()
const isExpanded = ref(false)
</script>
