// components/settings-card/index.vue
<template>
  <nuc-settings-card :heading="heading || t('settings-dock-style')">
    <ul class="settings-card-item-list">
      <li class="settings-card-item">
        <ad-label :label="t('settings-dock-style')" for="dock-style" />
        <ad-select-button
          id="dock-style"
          :model-value="toolbarStyle"
          :options="styleOptions"
          option-label="label"
          option-value="value"
          ad-type="main"
          @update:model-value="setToolbarStyle"
        />
      </li>
    </ul>
  </nuc-settings-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

import { NucSettingsCard, useToolbarStyle, type ToolbarStyle } from 'nucleify'

defineProps<{
  heading?: string
}>()

const { t } = useI18n()
const { toolbarStyle, setToolbarStyle } = useToolbarStyle()

const styleOptions = computed(() => [
  { label: t('settings-dock-style-dock'), value: 'dock' as ToolbarStyle },
  {
    label: t('settings-dock-style-sidebar'),
    value: 'sidebar' as ToolbarStyle,
  },
])
</script>

// components/settings-card/index.tsx
'use client'

import type { JSX } from 'react'
import { useMemo } from 'react'

import {
  AdLabel,
  AdSelectButton,
  NucSettingsCard,
  type ToolbarStyle,
  t,
  useToolbarStyle,
} from 'nucleify'

export interface NucDockSettingsCardInterface {
  heading?: string
}

export function NucDockSettingsCard({
  heading,
}: NucDockSettingsCardInterface): JSX.Element {
  const { toolbarStyle, setToolbarStyle } = useToolbarStyle()

  const styleOptions = useMemo(
    () => [
      {
        label: t('settings-dock-style-dock'),
        value: 'dock' as ToolbarStyle,
      },
      {
        label: t('settings-dock-style-sidebar'),
        value: 'sidebar' as ToolbarStyle,
      },
    ],
    []
  )

  return (
    <NucSettingsCard heading={heading || t('settings-dock-style')}>
      <ul className="settings-card-item-list">
        <li className="settings-card-item">
          <AdLabel label={t('settings-dock-style')} forInput="dock-style" />
          <AdSelectButton
            adType="main"
            value={toolbarStyle}
            options={styleOptions}
            optionLabel="label"
            optionValue="value"
            onChange={(event) => {
              const value = event.value
              if (value === 'dock' || value === 'sidebar') {
                setToolbarStyle(value)
              }
            }}
          />
        </li>
      </ul>
    </NucSettingsCard>
  )
}
